# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PromptlyJournals' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PromptlyJournals

 rn_path = '../node_modules/react-native'
   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
   pod 'React', path: rn_path, subspecs: [
     'Core',
     'RCTActionSheet',
     'RCTAnimation',
     'RCTGeolocation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTNetwork',
     'RCTSettings',
     'RCTText',
     'RCTVibration',
     'RCTWebSocket'
   ]

   pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
pod 'Mixpanel'
   pod 'Fabric'
   pod 'Crashlytics'


  #pod 'RNShare', :path => '../node_modules/react-native-share'

  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'Braintree'
    pod 'BraintreeDropIn'

    # comment the next line to disable Apple pay
    pod 'Braintree/Apple-Pay'

    # comment the next line to disable PayPal
    pod 'Braintree/PayPal'

    # comment the next line to disable Venmo
    pod 'Braintree/Venmo'

    # Data collector for Braintree Advanced Fraud Tools
    pod 'Braintree/DataCollector'

    # comment the next line to disable credit card scanning
    pod 'CardIO'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end


target 'PromptlyJournals-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PromptlyJournals-tvOS

  target 'PromptlyJournals-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
