import Config from './config';

export default {
    HTTP_SUCCESS_CODE: 200,
    HTTP_ERROR_CODE: 502,
    HTTP_CREATED_SUCCESS_CODE: 201,
    HTTP_PAGE_NOT_FOUND: 404,
    SERVER_NOT_FOUND: 500,
    UNAUTHORIZED_ACCESS_FOUND_CODE: 401,
    REQUEST_CODE_FAILED: 400,

    THEME_COLOR: '#fff',
    BACKGROUND_COLOR: '#f1f3f6',
    SPINNER_COLOR: '#736063',
    TEXT_COLOR: '#736063',
    WHITE_COLOR: '#fff',

    HEADER_FONT: 'Roboto-Regular',
    SUB_HEADER_FONT: 'Lato-Bold',
    PARAGRAPH_TEXT_FONT: 'Lato-Regular',
    TEXT_FONT: 'Bodoni',

    DEFAULT_PROFILE_IMAGE: `${Config.BASE_URL}/public/images/profiles/default.png`,
    DEFAULT_JOURNAL_IMAGE: `${Config.BASE_URL}/public/images/journals/default.jpg`,

    JOURNAL_IMAGE_LIMIT: 10,
    MAX_IMAGE_SIZE: 26214400,

    PRIVACY_POLICIES: 'https://promptlyjournals.com/pages/privacy-policy',
    TERMSANDCONDITIONS: 'https://promptlyjournals.com/pages/terms-of-use',
    FAQ: 'http://app.promptlyjournals.com/faq',
    GOOGLE_PDF_VIEWER: 'https://drive.google.com/viewerng/viewer?embedded=true&url=',

    NETWORK_ERROR: 'Network error, please try again',
    REQ_FAILED: 'Sorry, we couldn\'t complete your request. Please try again in a moment.',

    DUE_DATE_EMPTY: 'Due date is required',
    BIRTH_DATE_EMPTY: 'Birth date is required',
    EMAIL_EMPTY: 'Email is required',
    FIRST_NAME_EMPTY: 'First Name is required',
    FIRST_NAME_INVALID: 'First Name is invalid',
    LAST_NAME_EMPTY: 'Last Name is required',
    LAST_NAME_INVALID: 'Last Name is invalid',
    PASSWORD_EMPTY: 'Password is required',
    RESET_CODE_EMPTY: 'Reset Code is required',
    EMAIL_INVALID: 'Email is invalid',
    FILL_FULL_ENTRY: 'Fill out all the required entries',
    PASSWORD_LENGTH_INVALID: 'Password must be at least 8 characters long',
    PASSWORD_INVALID: 'Password should not contain spaces',
    NAME_EMPTY: 'Name is required',
    PASSWORD_NOT_MATCH: 'Password doesn\'t match.',
    PROFILE_UPDATE_SUCCESS: 'Profile updated successfully.',
    CHANGE_PASSWORD_SUCCESS: 'Password updated successfully.',
    CREATE_JOURNAL_SUCCESS: 'Journal Created successfully.',
    SAVE_JOURNAL_SUCCESS: 'Journal Updated successfully.',
    IMAGE_UPLOAD_SUCCESS: 'Image Uploaded successfully.',
    IMAGE_UPLOAD_LIMIT: 'Prompt Image must be less than equal to 10MB.',
    IMAGE_UPLOAD_SIZE_LIMIT: 'Image size must be less than or equal to 25MB.',
    IMAGE_DELETE_SUCCESS: 'Image deleted successfully.',
    IMAGE_EDIT_SUCCESS: 'Image updated successfully.',
    LOGIN_SUCCESS: 'Logged in successfully.',
    SIGNUP_SUCCESS: 'Registered successfully.',
    LOGOUT_SUCCESS: 'Logged out successfully.',
    PROMPT_SAVE_SUCCESS: 'Prompt Saved successfully.',
    CHANGE_PASSWORD_SUCCESS_1: 'Changed password successfully.',
    DUPLICATE_PROMPT_SUCCESS: 'Prompt copied successfully.',
    DELETE_PROMPT_SUCCESS: 'Prompt deleted successfully.',
    MOVE_PROMPT_SUCCESS: 'Prompt moved successfully.',
    DATE_CHANGE_SUCCESS: 'Date updated successfully.',
    AUTHOR_CHANGE_SUCCESS: 'Author updated successfully.',
    CUSTOM_PROMPT_SUCCESS: 'Custom Prompt created successfully.',
    PASSCODE_EMPTY: 'Passcode is required',
    PASSCODE_LENGTH_INVALID: 'Passcode must be 4 digits long',
    PASSCODE_SPACE_INVALID: 'Passcode should not contain spaces',
    PASSCODE_INVALID: 'Passcode should be numeric',
    SECURE_LOGIN_SUCCESS: 'Correct Passcode',
    CHECKBOX: 'Please accept the Terms and Conditions',
    PAYMENT_MODE: 'Please add a Payment Mode',
    VALID_PROMOCODE: 'Please enter a valid Promo code',
    DELETE_JOURNAL_SUCCESS: 'Journal deleted successfully.',
    CREATE_JOURNAL_SUCCESS_NOTE: 'Journal dates & names can not be edited. If you made a mistake, delete your journal and make a new one before you log any entries.',
    PLEASE_NOTE: 'PLEASE NOTE:',
    INVALID_PUSH_NOTIFICATION_FREQUENCY: 'Please select the frequency of push notifications',
    INVALID_PUSH_NOTIFICATION_FREQUENCY_PERIOD: 'Please select the period for push notifications',
    INVALID_PUSH_NOTIFICATION_WEEKDAYS: 'Please select the days of the week in which you are available for push notifications',
    INVALID_PUSH_NOTIFICATION_TIME: 'Please select the times of those days you would like to be prompted',
    INVALID_PUSH_NOTIFICATION_TIMEZONE: 'Please select the Time Zone',
    INVALID_PAYMENT: 'Unable to process the payment, please login and try again',
    PUSH_NOTIFICATION_SETTINGS_UPDATE_SUCCESS: 'Push notification settings successfully updated.',
    SHOW_PLATFORM_MESSAGE_ANDROID: 'You have Subscribed through ANDROID! Manage your subscription through your android device\'s Settings Screen',
    SHOW_PLATFORM_MESSAGE_APPLE: 'You have Subscribed through APPLE! Manage your subscription through your apple device\'s Settings Screen',
    SHOW_PLATFORM_MESSAGE_WEB: 'You have Subscribed through our WEBSITE! Manage or cancel your subscription through our website\'s Settings Page',
    NOTIFICATION_STATUS_SUCCESS: 'Notification status updated successfully',
    PDF_LOADING_TEXT: 'We\'re gathering your journal entries now. Sit tight - we\'ll have it ready in a moment..',

    SIGNUP_TEXT: 'Sign up for an account to take advantage of order history as well as pre-filled forms during checkout on subsequent orders.',
    FORGOT_PASSWORD_TEXT: 'We’ll send you an email to reset your password.',
    FORGOT_PASSCODE_TEXT: 'We’ll send you an email to reset your passcode.',
    COUPON_TEXT: 'USE CODE MOTHERSDAY FOR 20% OFF PRINTING ORDERS',
    BLANK_JOURNAL_TEXT: 'Your journals will go here',
    BLANK_PROMPT_TEXT: 'Your journal prompts will go here',
    PRINTED_PROMPT_TEXT: 'This prompt will be printed.',
    NOT_PRINTED_PROMPT_TEXT: 'This prompt will NOT be printed in your journal',
    NOT_PRINTED_PROMPT_2ND_TEXT: 'ANSWER THE PROMPT TO BE SHOWN IN PRINT',
    UNSUBSCRIBED_SUCCESSFULLY: 'Unsubscribed Successfully!',
    CHANGED_SUCCESSFULLY: 'Plan changed Successfully.',
    CHOOSE_PLAN: 'Please choose a plan to continue',
    EMPTY_CUSTOM_PROMPT: 'Please fill custom entry',
    SELECT_JOURNAL: 'Please select a section or subsection for custom entry',
    COMING_SOON: 'Search Function Coming Soon!',
    EMPTY_SECTION: 'There are no Sections or Subsections in the selected journal',
    ORDER_PLACED: 'Order Placed Successfully',
    NO_CART_ITEM: 'You don\'t have any items in your cart yet!',
    NO_JOURNAL_PRINT: 'Journal Not Available. Please create one to proceed further.',

    TOKEN: 'token',
    USER_ID: 'user_id',
    USER: 'user',
    EMAIL: 'email',

    DEVICE_TOKEN: '6a0974954e45d826239fc3c150734619745ca33e',
    UD_ID: '12345678',

    CHILDHOOD_JOURNAL: 'childhood',
    TRAVEL_JOURNAL: 'travel',
    LOVE_JOURNAL: 'love story',
    ADOPTION_JOURNAL: 'adoption',
    EVERYDAY_JOURNAL: 'everyday',
};
